# Name of the workflow - this appears in the GitHub Actions tab
name: CI/CD Pipeline

# Trigger the workflow on push or pull request events targeting the master branch
on:
  push:
    branches: [master]         # Runs when code is pushed to the 'master' branch
  pull_request:
    branches: [master]         # Runs when a pull request targets the 'master' branch

jobs:
  build:                     # Name of the job
    runs-on: ubuntu-latest   # Use the latest version of Ubuntu as the virtual machine

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      # This step checks out your repository so the workflow can access the code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'   # Specify the Python version you want to use

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip      # Upgrade pip to the latest version
        pip install -r requirements.txt          # Install project dependencies from requirements.txt

    - name: Run Linter
      run: |
        flake8 . --exclude=.venv                 # Run flake8 linter to check code style, excluding .venv folder

    - name: Run Tests
      run: |
        pytest                                   # Run all test cases using pytest
